<?php

namespace MoodMap\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecommendationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommendationRepository extends EntityRepository
{
}