MoodMapMapBundle:
    resource: "@MoodMapMapBundle/Resources/config/routing.yml"
    prefix:   /

MoodMapMainBundle:
    resource: "@MoodMapMainBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern: /
    defaults: { _controller: MoodMapMainBundle:Default:index }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
