MoodMapMapBundle_admin_recommendation:
    resource: "@MoodMapMapBundle/Resources/config/routing/recommendation.yml"
    prefix:   /admin/recommendation

search:
    pattern:  /map/search/{color}/{keyword}
    defaults: { _controller: MoodMapMapBundle:Map:search }
    requirements:
        _method: POST

createmap:
    pattern: /map/createmap/
    defaults: { _controller: MoodMapMapBundle:Map:createMap }

show_item:
    pattern:  /map/show
    defaults: { _controller: MoodMapMapBundle:Map:showItem }

createemotigramm:
    pattern:  /map/createemotigramm/
    defaults: { _controller: MoodMapMapBundle:Map:createEmotigramm }

#moodword

admin_moodword:
    pattern:  /admin/moodword/
    defaults: { _controller: "MoodMapMapBundle:MoodWord:index" }

admin_moodword_show:
    pattern:  /admin/moodword/{id}/show
    defaults: { _controller: "MoodMapMapBundle:MoodWord:show" }

admin_moodword_new:
    pattern:  /admin/moodword/new
    defaults: { _controller: "MoodMapMapBundle:MoodWord:new" }

admin_moodword_create:
    pattern:  /admin/moodword/create/{word}/{colors}
    defaults: { _controller: "MoodMapMapBundle:MoodWord:create" }
    requirements: { _method: post }

admin_moodword_edit:
    pattern:  /admin/moodword/{id}/edit
    defaults: { _controller: "MoodMapMapBundle:MoodWord:edit" }

admin_moodword_update:
    pattern:  /admin/moodword/{id}/update/{word}/{colors}
    defaults: { _controller: "MoodMapMapBundle:MoodWord:update" }
    requirements: { _method: post }

admin_moodword_delete:
    pattern:  /admin/moodword/{id}/delete
    defaults: { _controller: "MoodMapMapBundle:MoodWord:delete" }
    requirements: { _method: post }
