search:
    pattern:  /search/{color}/{keyword}
    defaults: { _controller: MoodMapMapBundle:Map:search }
    requirements:
        _method: POST

createmap:
    pattern: /createmap/
    defaults: { _controller: MoodMapMapBundle:Map:createMap }

show_item:
    pattern:  /show
    defaults: { _controller: MoodMapMapBundle:Map:showItem }