parameters:
#    mood_map_user.example.class: MoodMap\UserBundle\Example

services:
#    mood_map_user.example:
#        class: %mood_map_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
