parameters:
#    mood_map_user.example.class: MoodMap\UserBundle\Example

services:
#    mood_map_user.example:
#        class: %mood_map_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    moodmap_user.mood_provider:
        class: MoodMap\UserBundle\Security\Provider\MoodProvider
        public: false
        arguments: ["@fos_user.user_manager"]

    moodmap_user.registration.form.type:
            class: MoodMap\UserBundle\Form\Type\RegistrationFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: moodmap_user_registration }