parameters:
#    mood_map_main.example.class: MoodMap\MainBundle\Example

services:
#    mood_map_main.example:
#        class: %mood_map_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
