parameters:
#    mood_map_main.example.class: MoodMap\MainBundle\Example

services:
    authentication_handler:
        class: MoodMap\MainBundle\Handler\AuthenticationHandler
        arguments:  [@router]